"""Initial migration

Revision ID: caa06b2332fa
Revises: ee3c9b5b2bf6
Create Date: 2025-05-18 17:49:43.810795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa06b2332fa'
down_revision = 'ee3c9b5b2bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('doctor_count', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('patient_count', sa.Integer(), nullable=False),
    sa.Column('experience', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('org_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('ix_likes_comment_id')
        batch_op.drop_index('ix_likes_post_id')
        batch_op.drop_index('ix_likes_user_id')
        batch_op.drop_constraint('uq_user_comment_like', type_='unique')
        batch_op.drop_constraint('uq_user_post_like', type_='unique')
        batch_op.create_unique_constraint('unique_comment_like', ['user_id', 'comment_id'])
        batch_op.create_unique_constraint('unique_post_like', ['user_id', 'post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_post_like', type_='unique')
        batch_op.drop_constraint('unique_comment_like', type_='unique')
        batch_op.create_unique_constraint('uq_user_post_like', ['user_id', 'post_id'])
        batch_op.create_unique_constraint('uq_user_comment_like', ['user_id', 'comment_id'])
        batch_op.create_index('ix_likes_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_likes_post_id', ['post_id'], unique=False)
        batch_op.create_index('ix_likes_comment_id', ['comment_id'], unique=False)

    op.drop_table('org_specialties')
    op.drop_table('org_features')
    op.drop_table('doctor_profiles')
    op.drop_table('organization_profiles')
    # ### end Alembic commands ###
